#NAME:Bingxin Zhu
#EMAIL:bingxinzhu@g.ucla.edu
#ID:704845969

default:
	@gcc -o lab1a lab1a.c

clean:
	@rm -f lab1a lab1a-704845969.tar.gz

dist:
	@tar -czf lab1a-704845969.tar.gz lab1a.c Makefile README 
