#NAME: BingxinZhu
#EMAIL: bingxinzhu@ucla.edu
#ID: 704845969

FILES = lab3a.c Makefile README ext2_fs.h
default:
	gcc -g lab3a.c -o lab3a

dist:
	tar -czf lab3a-704845969.tar.gz $(FILES)

clean:
	rm -f lab3a *.csv *.tar.gz
